#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.oidc_name = "Outline"
    args.oidc_secret = "secret"
    args.oidc_callback = "domain.tld/callback"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.6ac2437d.name = "Upgrade from 2.37.0 (packaging v2)"
